name = "lapce-cpp-clangd"
display-name = "C/C++ (clangd)"
description = "C/C++ for Lapce: powered by clangd"
version = "0.0.1"
author = "panekj"
repository = "panekj/lapce-cpp-clangd"
wasm = "lapce-cpp-clangd.wasm"

[configuration]
language_id = "cpp"

[configuration.options.binary]
args = []
